SQL課題１
KakoFujimoto/quelcode-db pull request #1
Opened 2020-05-27 01:58 UTC by KakoFujimoto

- ER図をdraw.ioにて描画致しました
- 66b9c89 こちらのコミットです
- 指定のSQL教科書のような「1対0以上の多」を表すリレーションがなかったので「1 to Many」を使用しました

2020-05-27 02:29 UTC, piasoratech requested changes
この内容の場合チャットルームに参加しているユーザーを保持するテーブルが存在しないので、作成をしましょう。

2020-05-27 04:09 UTC, KakoFujimoto commented
9b4f347 こちらのコミットで「参加メンバー」エンティティと、付随するリレーションを追加致しました。

2020-05-27 07:20 UTC, piasoratech requested changes
参加メンバーのテーブルは何と何の紐づきを持つべきかもう一度考えてみましょう。
中間テーブルの考え方が役に立つかと思います。

2020-05-27 08:52 UTC, KakoFujimoto commented
986471a こちらのコミットで、どの参加メンバーがどのチャットルームに紐づいているかの「参加メンバー割」及び、どの参加メンバーがどのタスクと紐づいているかの「タスク割」のエンティティを追加致しました。

2020-05-28 06:04 UTC, KakoFujimoto commented
- 「参加メンバー割」、「タスク割」を削除
- 「チャンネル参加メンバー」を追加
-　 リレーションを見直し致しました
- 　
![Uploading スクリーンショット 2020-05-28 14.58.58.png…]()
１対多のリレーションですが、右から左への直線が更にひどいことになってますが、どうしようもありませんでした（キャプチャを参照下さい）

2020-05-28 06:33 UTC, piasoratech requested changes
線引きが大変カオスになってますが、こればっかしはしょうがないですね…笑
一点だけ指摘をさせてもらうと、中間テーブルのprimaryKeyAttributeの部分に「チャットルームid」と「ユーザーid」が入っていますが、これらは通常のAttributeとして記載して良いかと思います。(なのでPKがないテーブルの構成となる。)
その点だけ修正をお願いします。

![image](https://user-images.githubusercontent.com/57445698/83107013-71373b00-a0f8-11ea-9ac8-e754aef6e2ee.png)

2020-05-28 06:46 UTC, KakoFujimoto commented
- ご指摘の点、修正致しました！

2020-05-28 06:49 UTC, piasoratech requested changes
今の状態だと逆にすべてプライマリーキー側に入ってしまっているので逆ですね…
方眼が透けてる方にすべて書く感じです

2020-05-28 06:52 UTC, KakoFujimoto commented
今度こそ修正しました！
<img width="207" alt="スクリーンショット 2020-05-28 15 51 58" src="https://user-images.githubusercontent.com/60574321/83108786-439fc100-a0fb-11ea-8781-85a4d7ae3817.png">

2020-05-28 07:20 UTC, KakoFujimoto commented
チャンネル参加メンバーをPK２つ構成に再度変更致しました！
<img width="216" alt="スクリーンショット 2020-05-28 16 17 45" src="https://user-images.githubusercontent.com/60574321/83111137-1a812f80-a0ff-11ea-9c90-73740808fd59.png">

2020-05-28 07:23 UTC, piasoratech approved these changes
OKです
次に進みましょう！

2020-06-22 11:25 UTC, merged