SQL課題③の提出です
KakoFujimoto/quelcode-db pull request #3
Opened 2020-06-01 07:14 UTC by KakoFujimoto

やったこと
- 課題実行内容1〜12,14

できてないこと（現在確認中）
- 課題実行内容13のみ、現在質問中です（一応SQL文自体は通る状態なので提出させて頂きました）
phpMyAdminの仕様上の問題かもしれませんので、本来の運用目的からは外れますが、それ以外に関してレビューして頂ければ有り難いです。

2020-06-01 08:58 UTC, choimake reviewed
コメントしましたので確認お願いします。　

2020-06-01 08:58 UTC, choimake commented on db/db-challenge3/db-001/db-001.sql
> +( 11 , 'microsoft@gmail.com' , 'google' , 'amazon' , 'facebook' , NULL , '080-9999-5555' , 1 , 6 , '2020/04/24 06:00:02' , 1 , '2020/04/26 12:13:43');
`id`はauto_incrementなので、insert文に含める必要はありません。
その他のSQL文にも同様の箇所が見受けられますので、合わせて修正お願いします。

2020-06-01 09:19 UTC, KakoFujimoto commented on db/db-challenge3/db-001/db-001.sql
> +( 11 , 'microsoft@gmail.com' , 'google' , 'amazon' , 'facebook' , NULL , '080-9999-5555' , 1 , 6 , '2020/04/24 06:00:02' , 1 , '2020/04/26 12:13:43');
143ccff
こちらのコミットで修正致しました。

2020-06-02 06:41 UTC, choimake reviewed
db-005のinsertに不備を確認しています。
こちら修正の上、関連する他の課題のSQL文の実行を確認した後再度提出してください。

お手数おかけして申し訳ありませんが、対応お願いします。

2020-06-02 06:41 UTC, choimake commented on db/db-challenge3/db-005/db-005.sql
> +( 7 , '投稿が見えるかチェック' , 10 , 'NULL' , default , 1 , '2020/04/26 13:23:50' , 1 , '2020/04/26 13:23:50' , default);
文字列のNULLが残っています。
課題②のテーブルも修正しないと、insertが通らないはずなので課題②のddlと合わせて修正お願いします。
本当見落とし多くてすみません。

2020-06-02 08:27 UTC, fjtawork reviewed
11~13番までの見直しをお願いします！

2020-06-02 08:27 UTC, fjtawork commented on db/db-challenge3/db-011/db-011.sql
> +where created_at between '2020-04-26 09:00:00' and '2020-04-26 11:30:00' and is_deleted = 0;
課題の要件に下記がありまして、これがこのSQLだと条件に入っていないです。
> ユーザーの名前はadminであること

サブクエリ（副問合せ）やjoinを使ってusersテーブルでname=adminのuserを探して、そのidをupdate文の条件にしましょう。

僕ら人間はシートを見ればadminのusers.idが分かるので
今回 `update_user_id =1` と1を決め打ちで書けるのですが
DBは検索しないと名前がadminであるユーザを判別できないため。

11番以降のSQL文についても同じ事が言えそうなので、合わせて修正をお願いします。

2020-06-02 09:01 UTC, KakoFujimoto commented on db/db-challenge3/db-011/db-011.sql
> +where created_at between '2020-04-26 09:00:00' and '2020-04-26 11:30:00' and is_deleted = 0;
https://quelcode-kakelcode.slack.com/archives/GT8MYMWAC/p1591088257294100?thread_ts=1591081178.287400&cid=GT8MYMWAC
こちらご参照ください。カリキュラム上は修正不要となりました。

2020-06-02 09:18 UTC, fjtawork reviewed
さっきの指摘のミスはすいませんでした。
新しくコメントしましたので修正をお願いします！

2020-06-02 09:18 UTC, fjtawork commented on db/db-challenge3/db-006/db-006.sql
> +select id, email, password, name, self_intro, company_phone, cell_phone, is_deleted, create_user_id, created_at, update_user_id, updated_at from users;
要件の下記を修正しましょう！
order byを使います。

> ユーザidの昇順

2020-06-02 09:18 UTC, fjtawork commented on db/db-challenge3/db-007/db-007.sql
> +from chat_rooms where detail like '%ダイレクトチャット' and is_deleted = 0
こちらも要件のチャットルームIDでの昇順の並べ替えを実装しましょう。

2020-06-02 09:18 UTC, fjtawork commented on db/db-challenge3/db-010/db-010.sql
> +order by c.id
これもセミコロンですね

2020-06-02 09:24 UTC, KakoFujimoto commented on db/db-challenge3/db-010/db-010.sql
> +order by c.id
b36337a
こちらのコミットで修正致しました。凡ミス申し訳ございません…。

2020-06-02 09:28 UTC, KakoFujimoto commented on db/db-challenge3/db-007/db-007.sql
> +from chat_rooms where detail like '%ダイレクトチャット' and is_deleted = 0
0e7d30b
こちらのコミットでorder by句を追加いたしました。
a145989
こちらのコミットでキャプチャを差し替え致しました。

2020-06-02 09:33 UTC, KakoFujimoto commented on db/db-challenge3/db-006/db-006.sql
> +select id, email, password, name, self_intro, company_phone, cell_phone, is_deleted, create_user_id, created_at, update_user_id, updated_at from users;
bdcf259
こちらのコミットでorder by句を追加致しました。
3e0cb22
こちらのコミットで画像を差し替えました。

2020-06-02 09:37 UTC, KakoFujimoto commented
db-009.sqlにも文末にセミコロンが抜けていたので追加致しました。（925621f）

2020-06-03 07:24 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-06-03 07:24 UTC, piasoratech commented on db/db-challenge3/db-008/db-008.sql
> +order by join_time asc;
`order by`の昇順指定が他のSQLではされていないので、合わせておきましょう

2020-06-03 07:24 UTC, piasoratech commented on db/db-challenge3/db-014/db-014.sql
> +where u.is_deleted =1;
課題の書き方が悪くて申し訳ないのですが、削除するのは「チャットルームとユーザー」のリレーションであって、チャットルーム自体の削除は行いません。
確認と修正をお願いします。

2020-06-03 07:24 UTC, piasoratech commented on db/db-challenge3/db-012/db-012.sql
> +commit;
このSQLは要件を満たせていないので、確認と修正をお願いします。

2020-06-03 07:24 UTC, piasoratech commented on db/db-challenge3/db-010/db-010.sql
> +select u.name as '最新の投稿をしたユーザー名' , p.newest_posts as '投稿日時', c.name as 'チャットルーム名' , c.id as 'チャットルームid' from users as u
チャットルームidは表示する内容に含まれていないので、確認と修正をお願いします。

2020-06-03 07:49 UTC, KakoFujimoto commented on db/db-challenge3/db-010/db-010.sql
> +select u.name as '最新の投稿をしたユーザー名' , p.newest_posts as '投稿日時', c.name as 'チャットルーム名' , c.id as 'チャットルームid' from users as u
4ac51ea
こちらのコミットでチャットルームidを選択対象から除外しました
（今となっては問題文自体が変わってしまっているようですが、ご指摘の内容から照らし合わせてそこの修正のみ行いました）。

2020-06-03 07:52 UTC, KakoFujimoto commented on db/db-challenge3/db-008/db-008.sql
> +order by join_time asc;
db006〜010のみにorder by句の指定が必要かと思われますが、こちらで確認したところ、006〜010に関しては全てorder by句があるように思われます。現在、問題文が変わった場所もあり確認が取れないのですが、把握されてらっしゃるorder by句の抜け箇所を教えて頂けないでしょうか？

2020-06-03 08:35 UTC, KakoFujimoto commented on db/db-challenge3/db-008/db-008.sql
> +order by join_time asc;
7bf9564
このコミットでascの文言を除去し、他のSQL文と合わせました。

2020-06-03 09:47 UTC, KakoFujimoto commented on db/db-challenge3/db-012/db-012.sql
> +commit;
f8cf00b
b90d394
この２件のコミットで修正致しました。

2020-06-03 10:14 UTC, KakoFujimoto commented on db/db-challenge3/db-014/db-014.sql
> +where u.is_deleted =1;
92f3229
こちらのコミットで修正致しました。

2020-06-04 05:08 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-06-04 05:08 UTC, piasoratech commented on db/db-challenge3/db-012/db-012.sql
> +where is_deleted = 0 and id not in (select distinct chat_id from chat_members where user_id = (1) group by chat_id);
同じ課題のキャプチャのほうの指摘になりますが、チャットルームid6のis_sentは変わらず0のはずなので、確認をお願いします。
(今回の要件はadminがいない部屋のis_sentを0に変えるだけで、それ以外の動作は期待していないです。)

2020-06-04 05:36 UTC, KakoFujimoto commented on db/db-challenge3/db-012/db-012.sql
> +where is_deleted = 0 and id not in (select distinct chat_id from chat_members where user_id = (1) group by chat_id);
- そもそもdb-002.sqlのinsert文で、挿入するデータが誤っていたようです。

511f1d5
こちらのコミットで訂正しました。

- db-012.pngに関しては、正しい物を

7f63fae
こちらのコミットでアップしました。

2020-06-04 07:37 UTC, piasoratech approved these changes
修正確認しました！
お疲れ様でした！

2020-09-03 08:11 UTC, merged